# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('sales_data.csv')
print(df.head())

import pandas as pd

# Load dataset (you already uploaded it in Colab)
df = pd.read_csv('sales_data.csv')

# -----------------------------
# Data Cleaning
# -----------------------------

# Remove duplicates
df = df.drop_duplicates()

# Fill missing values (fixed version - no warnings)

# Numeric columns → fill with mean
for col in df.select_dtypes(include=['int64', 'float64']):
    df[col] = df[col].fillna(df[col].mean())

# Categorical columns → fill with mode
for col in df.select_dtypes(include=['object']):
    df[col] = df[col].fillna(df[col].mode()[0])


# -----------------------------
# Data Analysis (metrics)
# -----------------------------

# 1. Total Revenue
total_revenue = df['Total_Sales'].sum()

# 2. Average Revenue
avg_revenue = df['Total_Sales'].mean()

# 3. Best Selling Product
best_product = df.groupby('Product')['Total_Sales'].sum().idxmax()

# 4. Revenue by Region
revenue_by_region = df.groupby('Region')['Total_Sales'].sum()


# -----------------------------
# Final Report
# -----------------------------

print("===== SALES REPORT =====")
print(f"Total Revenue      : ₹{total_revenue:,.2f}")
print(f"Average Revenue    : ₹{avg_revenue:,.2f}")
print(f"Best Product       : {best_product}")

print("\nRevenue by Region:")
print(revenue_by_region)

print("\nInsights:")
print(f"- '{best_product}' is the top revenue-generating product.")
print("- Certain regions contribute more revenue — focus marketing there.")
print("- Improving low-performing products can increase overall sales.")
